export const SHIPPING_ATTRIBUTE_OPTIONS = [
  "Ordinary",
  "Clothes",
  "Electronic",
  "Battery Contains",
  "Pure Battery",
  "Liquid Contains",
  "Powder",
  "Cream",
  "Magnetic Contains",
  "Sharp",
  "Customs Ban",
  "Imitation Brand",
  "Oversize",
  "Thin",
  "Flat",
  "Glasses",
  "Plant",
  "High Power Pure Battery",
  "Alcoholic",
  "Liquid Contains (Above 100ml)",
  "Highly Magnetic",
  "Kitchen Knife",
  "Long Blade",
  "Ointment Patch",
  "Pressure Can",
  "Drone",
  "Laser",
  "Flint Contains",
  "Combustible",
  "Defensive Apparatus",
  "Shaped Appearance",
  "Powder (Within 500g)",
  "Special Product F",
  "Large Size",
  "Health Products",
  "POD2.0",
  "POD3.0",
  "Other",
] as const;

export type ShippingAttribute = (typeof SHIPPING_ATTRIBUTE_OPTIONS)[number];

export const DEFAULT_SHIPPING_ATTRIBUTE: ShippingAttribute = "Ordinary";