services:
  jevi-store:
    build:
      context: .
      dockerfile: Dockerfile
    image: jevi-store:local
    container_name: jevi-store-local
    env_file:
      - .env.local
    environment:
      NODE_ENV: production
      PORT: "3000"
      HOSTNAME: "0.0.0.0"

      # 容器服务端访问宿主机服务
      API_PROXY: http://host.docker.internal:8787
      AUTH_UPSTREAM: http://host.docker.internal:8787
      STRAPI_URL: http://host.docker.internal:1337

      # 浏览器访问宿主机服务
      NEXT_PUBLIC_API_BASE: http://127.0.0.1:8787
      NEXT_PUBLIC_STRAPI_URL: http://127.0.0.1:1337
      NEXT_PUBLIC_STOREFRONT_CODE: AU
    ports:
      - "3000:3000"
    restart: "no"